-- MySQL Script generated by MySQL Workbench
-- Thu Mar 16 13:52:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Filmy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Filmy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Filmy` DEFAULT CHARACTER SET utf8 ;
USE `Filmy` ;

-- -----------------------------------------------------
-- Table `Filmy`.`Film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Filmy`.`Film` (
  `idFilm` INT NOT NULL,
  `jmeno` VARCHAR(45) NULL,
  PRIMARY KEY (`idFilm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Filmy`.`Herec`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Filmy`.`Herec` (
  `idHerec` INT NOT NULL,
  `Film_idFilm` INT NOT NULL,
  `jmeno` VARCHAR(45) NULL,
  `prijemni` VARCHAR(45) NULL,
  PRIMARY KEY (`idHerec`, `Film_idFilm`),
  INDEX `fk_Herec_Film_idx` (`Film_idFilm` ASC),
  CONSTRAINT `fk_Herec_Film`
    FOREIGN KEY (`Film_idFilm`)
    REFERENCES `Filmy`.`Film` (`idFilm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
